spring:
    application:
        name: alejandro-test
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa:
        hibernate:
            ddl-auto: none
    h2:
        console:
            enabled: true
